name: "SDK Code Generation"
on:
  schedule:
    - cron: '*/5 * * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  generate_and_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Generate and PR
        uses: Eric-Warehime/generator/.github/actions/sdk-codegen/@sdk-generation
        with:
          args: "-k GO"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
